uint8 SCIENCE_TARE_ROCKS = 0x01
uint8 SCIENCE_REQUEST_ROCKS = 0x02
uint8 SCIENCE_TARE_SAMPLE = 0x03
uint8 SCIENCE_REQUEST_SAMPLE = 0x04
uint8 SCIENCE_TARE_DRILL = 0x05
uint8 SCIENCE_REQUEST_DRILL = 0x06

uint8 CONTAINER1_CLOSE = 0x08
uint8 CONTAINER1_OPEN = 0x09
uint8 CONTAINER2_CLOSE = 0x0A
uint8 CONTAINER2_OPEN = 0x0B

uint8 SCIENCE_AUTONOMY_RESET = 0x0C
uint8 SCIENCE_AUTONOMY_START = 0x0D
uint8 SCIENCE_AUTONOMY_PAUSE = 0x0E

uint8 cmd
uint8[] data
---
# no response