/**:
  ros__parameters:
    frame_id: base_link
    publish_tf: False
    approx_sync: False
    topic_queue_size: 1
    rgb_transport: compressed
    depth_transport: compressedDepth

    Odom/ResetCountdown: "1"
    Odom/Strategy: "0"
