# Common configuration of realsense2_camera nodes.
/**:
  ros__parameters:
    align_depth:
      enable: true
    enable_infra: false
    enable_infra1: false
    enable_infra2: false
    enable_gyro: false
    enable_accel: false
    publish_tf: true
    initial_reset: true
    rgb_camera:
      color_profile: 1280x720x30
      enable_auto_exposure: False
      exposure: 2 # FIXME: Change for indoor/outdoor mapping.; outdoor=2; indoor=200
    depth_module:
      depth_profile: 640x360x30
    clip_distance: 5.0
