# Common configuration of realsense2_camera nodes.
/**:
  ros__parameters:
    align_depth:
      enable: true
    enable_infra: false
    enable_infra1: false
    enable_infra2: false
    enable_gyro: false
    enable_accel: false
    publish_tf: true
    initial_reset: true
    rgb_camera:
      color_profile: 640x360x15
      enable_auto_exposure: False
      exposure: 3 # FIXME: Change for indoor/outdoor mapping.; outdoor=3; indoor=200
    depth_module:
      depth_profile: 640x360x15
    clip_distance: 5.0
