/**:
  ros__parameters:
    stateless: false
    use_mag: true
    publish_tf: false
    reverse_tf: false
    fixed_frame: "odom" # use with publish_tf
    constant_dt: 0.0
    remove_gravity_vector: false
    publish_debug_topics: false
    yaw_offset: 0.0
    # Declination should be set to a precise value,
    # so that the IMU points at the true north.
    # For now, this value can be read from online resources,
    # but it often must be adjusted experimentally
    # since there is are lots of EM sources onboard.
    declination: 0.110304716
    world_frame: "enu"
    gain: 0.01 # NOTE: Smaller value turned out to work better with the UKF.
    zeta: 0.0
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 1.0
    use_sim_time: false
