/**:
  ros__parameters:
    # # image transport for color images
    # color_transport: compressed
    # # image transport for depth images
    # depth_transport: compressedDepth
    # ^ Set in launch file
    # horizontal resolution of the point cloud
    cloud_width: 200
    # minimum Z coordinate of a point to be included in the point cloud
    min_distance: 0.1
    # maximum Z coordinate of a point to be included in the point cloud
    max_distance: 5.0
