# This is not a ROS 2 parameter file, but a custom YAML config.

rover: # or 'station'
  topics: # topics published by the rover and subscribed by the GS
    - name: imu/data
      type: sensor_msgs/msg/Imu
      max_rate: 5
      fields:
        - path: orientation
          float_range: # skip header, velocity and acceleration
            min: -1.0
            max: 1.0
            bytes: 1 # precision = 0.008; will un-normalize the quaternion a bit
    - name: gps/fix
      type: sensor_msgs/msg/NavSatFix
      max_rate: 2
      fields:
        - path: status.status
          int_range:
            min: -1 # min status.status
            max: 2 # max status.status
        - path: latitude
          float_range:
            min: -90.0
            max: 90.0
            bytes: 4 # precision = 0.00000005 degrees = 0.5 cm
        - path: longitude
          float_range:
            min: -180.0
            max: 180.0
            bytes: 4 # precision = 0.0000001 degrees = 1 cm
    - name: gps/filtered
      type: sensor_msgs/msg/NavSatFix
      max_rate: 2
      fields:
        - path: status.status
          int_range:
            min: -1 # min status.status
            max: 2 # max status.status
        - path: latitude
          float_range:
            min: -90.0
            max: 90.0
            bytes: 4 # precision = 0.00000005 degrees = 0.5 cm
        - path: longitude
          float_range:
            min: -180.0
            max: 180.0
            bytes: 4 # precision = 0.0000001 degrees = 1 cm
    - name: odometry/global
      type: nav_msgs/msg/Odometry
      max_rate: 2
      fields:
        - path: pose.pose.orientation
          min: -1.0
          max: 1.0
          bytes: 1
    # - name: test_string
    #   type: example_interfaces/msg/String
    #   string_enum:
    #     fallback: unknown
    #     values:
    #       - teleop
    #       - prepare
    #       - travel
    #       - stop_to_teleop
    #       - stop_to_finished
    #       - finished
  services:
    - name: spoof_gps
      type: kalman_interfaces/srv/SpoofGps
      request_fields:
        - path: location.latitude
          float_range:
            min: -90.0
            max: 90.0
            bytes: 4 # precision = 0.00000005 degrees = 0.5 cm
        - path: location.longitude
          float_range:
            min: -180.0
            max: 180.0
            bytes: 4 # precision = 0.0000001 degrees = 1 cm
    - name: spoof_gps/look_at
      type: kalman_interfaces/srv/SpoofGps
      request_fields:
        - path: location.latitude
          float_range:
            min: -90.0
            max: 90.0
            bytes: 4 # precision = 0.00000005 degrees = 0.5 cm
        - path: location.longitude
          float_range:
            min: -180.0
            max: 180.0
            bytes: 4 # precision = 0.0000001 degrees = 1 cm
    # - name: add_two_ints
    #   type: example_interfaces/srv/AddTwoInts
    #   retry_rate: 5
  actions: # actions served by the rover and used by the GS
    # - name: fibonacci
    #   type: example_interfaces/action/Fibonacci
    #   retry_rate: 10
    #   max_feedback_rate: 0.5
    - name: supervisor/tf_goal
      type: kalman_interfaces/action/SupervisorTfGoal
      max_feedback_rate: 1
      goal_fields:
        - path: location.header.frame_id
          string_enum: # When serializing a string which can have a limited set of values, use a single byte int instead of storing plain text.
            - base_link
            - odom
            - map
            - utm
        - location.point # shorthand without quantization
      float_range: # common quantization for all float fields; Affects location.point which does not specify a range.
        min: -10000.0
        max: 10000.0
        bytes: 2 # precision = 0.3 m
      string_enum: # This global enum will be used for other fields, in this case for feedback state.
        fallback: unknown # when a string in a field does not match any of the values, fall back to this value
        values:
          - teleop
          - prepare
          - travel
          - stop_to_teleop
          - stop_to_finished
          - finished
    - name: supervisor/gps_goal
      type: kalman_interfaces/action/SupervisorGpsGoal
      max_feedback_rate: 1
      goal_fields:
        - location.latitude
        - location.longitude
      float_range:
        min: -180.0
        max: 180.0
        bytes: 4 # precision = 0.0000001 degrees = 1 cm
      feedback_fields:
        - path: "" # empty path matches all fields
          string_enum: # Specify ranges or enum in a field to limit its scope. Here done just for demo purposes.
            fallback: unknown
            values:
              - teleop
              - prepare
              - travel
              - stop_to_teleop
              - stop_to_finished
              - finished
    - name: supervisor/gps_aruco_search
      type: kalman_interfaces/action/SupervisorGpsArUcoSearch
      max_feedback_rate: 1
      goal_fields:
        - initial_location.latitude
        - initial_location.longitude
        - marker_id
      feedback_fields:
        - state
        - marker_found
        - marker_location.latitude
        - marker_location.longitude
      int_range:
        min: 0
        max: 49 # ArUco 4X4_50 dictionary
      float_range:
        min: -180.0
        max: 180.0
        bytes: 4 # precision = 0.0000001 degrees = 1 cm
      string_enum:
        fallback: unknown
        values:
          - teleop
          - prepare
          - travel
          - stop_to_teleop
          - stop_to_finished
          - finished
          - search_for_aruco
          - approach
    - name: supervisor/gps_yolo_search
      type: kalman_interfaces/action/SupervisorGpsYoloSearch
      max_feedback_rate: 1
      goal_fields:
        - initial_location.latitude
        - initial_location.longitude
        - object_class
      feedback_fields:
        - state
        - object_found
        - object_location.latitude
        - object_location.longitude
      float_range:
        min: -180.0
        max: 180.0
        bytes: 4 # precision = 0.0000001 degrees = 1 cm
      string_enum:
        fallback: unknown
        values:
          - teleop
          - prepare
          - travel
          - stop_to_teleop
          - stop_to_finished
          - finished
          - search_for_yolo
          - approach
          - mallet # not a state, but a possible object_class value
          - bottle

# station:
  # topics: {} # topics published by the GS and subscribed by the rover
