# (0,0) --> (u)
#   |
#   |
#   v
#  (v)
markers:
  13: {u: 0.0, v: 0.0}          # top-left is (0,0)
  14: {u: 0.261, v: 0.0, yaw_deg: 0}
  15: {u: 0.0, v: 0.381}
marker_size: 0.050   # meters (edge length)
board_width: 0.400   # meters
board_height: 0.600  # meters
