name: PR Format Check

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  call-parent-format-check:
    uses: agh-space-systems-rover/kalman-ws/.github/workflows/format-check.yml@ci/format-check-workflow/v1
    with:
      paths: .
